// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hyperledger/fabric-sdk-go/pkg/context (interfaces: BaseProviders)

// Package mock_context is a generated GoMock package.
package mock_context

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/hyperledger/fabric-sdk-go/pkg/context/api/core"
	fab "github.com/hyperledger/fabric-sdk-go/pkg/context/api/fab"
)

// MockBaseProviders is a mock of BaseProviders interface
type MockBaseProviders struct {
	ctrl     *gomock.Controller
	recorder *MockBaseProvidersMockRecorder
}

// MockBaseProvidersMockRecorder is the mock recorder for MockBaseProviders
type MockBaseProvidersMockRecorder struct {
	mock *MockBaseProviders
}

// NewMockBaseProviders creates a new mock instance
func NewMockBaseProviders(ctrl *gomock.Controller) *MockBaseProviders {
	mock := &MockBaseProviders{ctrl: ctrl}
	mock.recorder = &MockBaseProvidersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBaseProviders) EXPECT() *MockBaseProvidersMockRecorder {
	return m.recorder
}

// ChannelProvider mocks base method
func (m *MockBaseProviders) ChannelProvider() fab.ChannelProvider {
	ret := m.ctrl.Call(m, "ChannelProvider")
	ret0, _ := ret[0].(fab.ChannelProvider)
	return ret0
}

// ChannelProvider indicates an expected call of ChannelProvider
func (mr *MockBaseProvidersMockRecorder) ChannelProvider() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChannelProvider", reflect.TypeOf((*MockBaseProviders)(nil).ChannelProvider))
}

// Config mocks base method
func (m *MockBaseProviders) Config() core.Config {
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(core.Config)
	return ret0
}

// Config indicates an expected call of Config
func (mr *MockBaseProvidersMockRecorder) Config() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockBaseProviders)(nil).Config))
}

// CryptoSuite mocks base method
func (m *MockBaseProviders) CryptoSuite() core.CryptoSuite {
	ret := m.ctrl.Call(m, "CryptoSuite")
	ret0, _ := ret[0].(core.CryptoSuite)
	return ret0
}

// CryptoSuite indicates an expected call of CryptoSuite
func (mr *MockBaseProvidersMockRecorder) CryptoSuite() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CryptoSuite", reflect.TypeOf((*MockBaseProviders)(nil).CryptoSuite))
}

// DiscoveryProvider mocks base method
func (m *MockBaseProviders) DiscoveryProvider() fab.DiscoveryProvider {
	ret := m.ctrl.Call(m, "DiscoveryProvider")
	ret0, _ := ret[0].(fab.DiscoveryProvider)
	return ret0
}

// DiscoveryProvider indicates an expected call of DiscoveryProvider
func (mr *MockBaseProvidersMockRecorder) DiscoveryProvider() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoveryProvider", reflect.TypeOf((*MockBaseProviders)(nil).DiscoveryProvider))
}

// FabricProvider mocks base method
func (m *MockBaseProviders) FabricProvider() fab.FabricProvider {
	ret := m.ctrl.Call(m, "FabricProvider")
	ret0, _ := ret[0].(fab.FabricProvider)
	return ret0
}

// FabricProvider indicates an expected call of FabricProvider
func (mr *MockBaseProvidersMockRecorder) FabricProvider() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FabricProvider", reflect.TypeOf((*MockBaseProviders)(nil).FabricProvider))
}

// SelectionProvider mocks base method
func (m *MockBaseProviders) SelectionProvider() fab.SelectionProvider {
	ret := m.ctrl.Call(m, "SelectionProvider")
	ret0, _ := ret[0].(fab.SelectionProvider)
	return ret0
}

// SelectionProvider indicates an expected call of SelectionProvider
func (mr *MockBaseProvidersMockRecorder) SelectionProvider() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectionProvider", reflect.TypeOf((*MockBaseProviders)(nil).SelectionProvider))
}

// SigningManager mocks base method
func (m *MockBaseProviders) SigningManager() core.SigningManager {
	ret := m.ctrl.Call(m, "SigningManager")
	ret0, _ := ret[0].(core.SigningManager)
	return ret0
}

// SigningManager indicates an expected call of SigningManager
func (mr *MockBaseProvidersMockRecorder) SigningManager() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SigningManager", reflect.TypeOf((*MockBaseProviders)(nil).SigningManager))
}

// StateStore mocks base method
func (m *MockBaseProviders) StateStore() core.KVStore {
	ret := m.ctrl.Call(m, "StateStore")
	ret0, _ := ret[0].(core.KVStore)
	return ret0
}

// StateStore indicates an expected call of StateStore
func (mr *MockBaseProvidersMockRecorder) StateStore() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateStore", reflect.TypeOf((*MockBaseProviders)(nil).StateStore))
}
