// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/hyperledger/fabric-sdk-go/api/apifabclient (interfaces: ProposalProcessor)

package mock_apifabclient

import (
	gomock "github.com/golang/mock/gomock"
	apifabclient "github.com/hyperledger/fabric-sdk-go/api/apifabclient"
)

// MockProposalProcessor interface
type MockProposalProcessor struct {
	ctrl     *gomock.Controller
	recorder *_MockProposalProcessorRecorder
}

// Recorder for MockProposalProcessor (not exported)
type _MockProposalProcessorRecorder struct {
	mock *MockProposalProcessor
}

// NewMockProposalProcessor creates a new mock instance
func NewMockProposalProcessor(ctrl *gomock.Controller) *MockProposalProcessor {
	mock := &MockProposalProcessor{ctrl: ctrl}
	mock.recorder = &_MockProposalProcessorRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockProposalProcessor) EXPECT() *_MockProposalProcessorRecorder {
	return _m.recorder
}

// ProcessTransactionProposal mocks base method
func (_m *MockProposalProcessor) ProcessTransactionProposal(_param0 apifabclient.TransactionProposal) (apifabclient.TransactionProposalResponse, error) {
	ret := _m.ctrl.Call(_m, "ProcessTransactionProposal", _param0)
	ret0, _ := ret[0].(apifabclient.TransactionProposalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessTransactionProposal indicates an expected call of ProcessTransactionProposal
func (_mr *_MockProposalProcessorRecorder) ProcessTransactionProposal(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ProcessTransactionProposal", arg0)
}
