// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hyperledger/fabric-sdk-go/pkg/common/providers/context (interfaces: Providers,Client)

package mockcontext

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/hyperledger/fabric-sdk-go/pkg/common/providers/core"
	fab "github.com/hyperledger/fabric-sdk-go/pkg/common/providers/fab"
	msp "github.com/hyperledger/fabric-sdk-go/pkg/common/providers/msp"
)

// MockProviders is a mock of Providers interface
type MockProviders struct {
	ctrl     *gomock.Controller
	recorder *MockProvidersMockRecorder
}

// MockProvidersMockRecorder is the mock recorder for MockProviders
type MockProvidersMockRecorder struct {
	mock *MockProviders
}

// NewMockProviders creates a new mock instance
func NewMockProviders(ctrl *gomock.Controller) *MockProviders {
	mock := &MockProviders{ctrl: ctrl}
	mock.recorder = &MockProvidersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockProviders) EXPECT() *MockProvidersMockRecorder {
	return _m.recorder
}

// ChannelProvider mocks base method
func (_m *MockProviders) ChannelProvider() fab.ChannelProvider {
	ret := _m.ctrl.Call(_m, "ChannelProvider")
	ret0, _ := ret[0].(fab.ChannelProvider)
	return ret0
}

// ChannelProvider indicates an expected call of ChannelProvider
func (_mr *MockProvidersMockRecorder) ChannelProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ChannelProvider", reflect.TypeOf((*MockProviders)(nil).ChannelProvider))
}

// CryptoSuite mocks base method
func (_m *MockProviders) CryptoSuite() core.CryptoSuite {
	ret := _m.ctrl.Call(_m, "CryptoSuite")
	ret0, _ := ret[0].(core.CryptoSuite)
	return ret0
}

// CryptoSuite indicates an expected call of CryptoSuite
func (_mr *MockProvidersMockRecorder) CryptoSuite() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CryptoSuite", reflect.TypeOf((*MockProviders)(nil).CryptoSuite))
}

// DiscoveryProvider mocks base method
func (_m *MockProviders) DiscoveryProvider() fab.DiscoveryProvider {
	ret := _m.ctrl.Call(_m, "DiscoveryProvider")
	ret0, _ := ret[0].(fab.DiscoveryProvider)
	return ret0
}

// DiscoveryProvider indicates an expected call of DiscoveryProvider
func (_mr *MockProvidersMockRecorder) DiscoveryProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DiscoveryProvider", reflect.TypeOf((*MockProviders)(nil).DiscoveryProvider))
}

// EndpointConfig mocks base method
func (_m *MockProviders) EndpointConfig() fab.EndpointConfig {
	ret := _m.ctrl.Call(_m, "EndpointConfig")
	ret0, _ := ret[0].(fab.EndpointConfig)
	return ret0
}

// EndpointConfig indicates an expected call of EndpointConfig
func (_mr *MockProvidersMockRecorder) EndpointConfig() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "EndpointConfig", reflect.TypeOf((*MockProviders)(nil).EndpointConfig))
}

// IdentityConfig mocks base method
func (_m *MockProviders) IdentityConfig() msp.IdentityConfig {
	ret := _m.ctrl.Call(_m, "IdentityConfig")
	ret0, _ := ret[0].(msp.IdentityConfig)
	return ret0
}

// IdentityConfig indicates an expected call of IdentityConfig
func (_mr *MockProvidersMockRecorder) IdentityConfig() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IdentityConfig", reflect.TypeOf((*MockProviders)(nil).IdentityConfig))
}

// IdentityManager mocks base method
func (_m *MockProviders) IdentityManager(_param0 string) (msp.IdentityManager, bool) {
	ret := _m.ctrl.Call(_m, "IdentityManager", _param0)
	ret0, _ := ret[0].(msp.IdentityManager)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IdentityManager indicates an expected call of IdentityManager
func (_mr *MockProvidersMockRecorder) IdentityManager(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IdentityManager", reflect.TypeOf((*MockProviders)(nil).IdentityManager), arg0)
}

// InfraProvider mocks base method
func (_m *MockProviders) InfraProvider() fab.InfraProvider {
	ret := _m.ctrl.Call(_m, "InfraProvider")
	ret0, _ := ret[0].(fab.InfraProvider)
	return ret0
}

// InfraProvider indicates an expected call of InfraProvider
func (_mr *MockProvidersMockRecorder) InfraProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "InfraProvider", reflect.TypeOf((*MockProviders)(nil).InfraProvider))
}

// LocalDiscoveryProvider mocks base method
func (_m *MockProviders) LocalDiscoveryProvider() fab.LocalDiscoveryProvider {
	ret := _m.ctrl.Call(_m, "LocalDiscoveryProvider")
	ret0, _ := ret[0].(fab.LocalDiscoveryProvider)
	return ret0
}

// LocalDiscoveryProvider indicates an expected call of LocalDiscoveryProvider
func (_mr *MockProvidersMockRecorder) LocalDiscoveryProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "LocalDiscoveryProvider", reflect.TypeOf((*MockProviders)(nil).LocalDiscoveryProvider))
}

// SelectionProvider mocks base method
func (_m *MockProviders) SelectionProvider() fab.SelectionProvider {
	ret := _m.ctrl.Call(_m, "SelectionProvider")
	ret0, _ := ret[0].(fab.SelectionProvider)
	return ret0
}

// SelectionProvider indicates an expected call of SelectionProvider
func (_mr *MockProvidersMockRecorder) SelectionProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectionProvider", reflect.TypeOf((*MockProviders)(nil).SelectionProvider))
}

// SigningManager mocks base method
func (_m *MockProviders) SigningManager() core.SigningManager {
	ret := _m.ctrl.Call(_m, "SigningManager")
	ret0, _ := ret[0].(core.SigningManager)
	return ret0
}

// SigningManager indicates an expected call of SigningManager
func (_mr *MockProvidersMockRecorder) SigningManager() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SigningManager", reflect.TypeOf((*MockProviders)(nil).SigningManager))
}

// UserStore mocks base method
func (_m *MockProviders) UserStore() msp.UserStore {
	ret := _m.ctrl.Call(_m, "UserStore")
	ret0, _ := ret[0].(msp.UserStore)
	return ret0
}

// UserStore indicates an expected call of UserStore
func (_mr *MockProvidersMockRecorder) UserStore() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UserStore", reflect.TypeOf((*MockProviders)(nil).UserStore))
}

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClient) EXPECT() *MockClientMockRecorder {
	return _m.recorder
}

// ChannelProvider mocks base method
func (_m *MockClient) ChannelProvider() fab.ChannelProvider {
	ret := _m.ctrl.Call(_m, "ChannelProvider")
	ret0, _ := ret[0].(fab.ChannelProvider)
	return ret0
}

// ChannelProvider indicates an expected call of ChannelProvider
func (_mr *MockClientMockRecorder) ChannelProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ChannelProvider", reflect.TypeOf((*MockClient)(nil).ChannelProvider))
}

// CryptoSuite mocks base method
func (_m *MockClient) CryptoSuite() core.CryptoSuite {
	ret := _m.ctrl.Call(_m, "CryptoSuite")
	ret0, _ := ret[0].(core.CryptoSuite)
	return ret0
}

// CryptoSuite indicates an expected call of CryptoSuite
func (_mr *MockClientMockRecorder) CryptoSuite() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CryptoSuite", reflect.TypeOf((*MockClient)(nil).CryptoSuite))
}

// DiscoveryProvider mocks base method
func (_m *MockClient) DiscoveryProvider() fab.DiscoveryProvider {
	ret := _m.ctrl.Call(_m, "DiscoveryProvider")
	ret0, _ := ret[0].(fab.DiscoveryProvider)
	return ret0
}

// DiscoveryProvider indicates an expected call of DiscoveryProvider
func (_mr *MockClientMockRecorder) DiscoveryProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DiscoveryProvider", reflect.TypeOf((*MockClient)(nil).DiscoveryProvider))
}

// EndpointConfig mocks base method
func (_m *MockClient) EndpointConfig() fab.EndpointConfig {
	ret := _m.ctrl.Call(_m, "EndpointConfig")
	ret0, _ := ret[0].(fab.EndpointConfig)
	return ret0
}

// EndpointConfig indicates an expected call of EndpointConfig
func (_mr *MockClientMockRecorder) EndpointConfig() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "EndpointConfig", reflect.TypeOf((*MockClient)(nil).EndpointConfig))
}

// EnrollmentCertificate mocks base method
func (_m *MockClient) EnrollmentCertificate() []byte {
	ret := _m.ctrl.Call(_m, "EnrollmentCertificate")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// EnrollmentCertificate indicates an expected call of EnrollmentCertificate
func (_mr *MockClientMockRecorder) EnrollmentCertificate() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "EnrollmentCertificate", reflect.TypeOf((*MockClient)(nil).EnrollmentCertificate))
}

// Identifier mocks base method
func (_m *MockClient) Identifier() *msp.IdentityIdentifier {
	ret := _m.ctrl.Call(_m, "Identifier")
	ret0, _ := ret[0].(*msp.IdentityIdentifier)
	return ret0
}

// Identifier indicates an expected call of Identifier
func (_mr *MockClientMockRecorder) Identifier() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Identifier", reflect.TypeOf((*MockClient)(nil).Identifier))
}

// IdentityConfig mocks base method
func (_m *MockClient) IdentityConfig() msp.IdentityConfig {
	ret := _m.ctrl.Call(_m, "IdentityConfig")
	ret0, _ := ret[0].(msp.IdentityConfig)
	return ret0
}

// IdentityConfig indicates an expected call of IdentityConfig
func (_mr *MockClientMockRecorder) IdentityConfig() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IdentityConfig", reflect.TypeOf((*MockClient)(nil).IdentityConfig))
}

// IdentityManager mocks base method
func (_m *MockClient) IdentityManager(_param0 string) (msp.IdentityManager, bool) {
	ret := _m.ctrl.Call(_m, "IdentityManager", _param0)
	ret0, _ := ret[0].(msp.IdentityManager)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IdentityManager indicates an expected call of IdentityManager
func (_mr *MockClientMockRecorder) IdentityManager(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IdentityManager", reflect.TypeOf((*MockClient)(nil).IdentityManager), arg0)
}

// InfraProvider mocks base method
func (_m *MockClient) InfraProvider() fab.InfraProvider {
	ret := _m.ctrl.Call(_m, "InfraProvider")
	ret0, _ := ret[0].(fab.InfraProvider)
	return ret0
}

// InfraProvider indicates an expected call of InfraProvider
func (_mr *MockClientMockRecorder) InfraProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "InfraProvider", reflect.TypeOf((*MockClient)(nil).InfraProvider))
}

// LocalDiscoveryProvider mocks base method
func (_m *MockClient) LocalDiscoveryProvider() fab.LocalDiscoveryProvider {
	ret := _m.ctrl.Call(_m, "LocalDiscoveryProvider")
	ret0, _ := ret[0].(fab.LocalDiscoveryProvider)
	return ret0
}

// LocalDiscoveryProvider indicates an expected call of LocalDiscoveryProvider
func (_mr *MockClientMockRecorder) LocalDiscoveryProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "LocalDiscoveryProvider", reflect.TypeOf((*MockClient)(nil).LocalDiscoveryProvider))
}

// PrivateKey mocks base method
func (_m *MockClient) PrivateKey() core.Key {
	ret := _m.ctrl.Call(_m, "PrivateKey")
	ret0, _ := ret[0].(core.Key)
	return ret0
}

// PrivateKey indicates an expected call of PrivateKey
func (_mr *MockClientMockRecorder) PrivateKey() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "PrivateKey", reflect.TypeOf((*MockClient)(nil).PrivateKey))
}

// PublicVersion mocks base method
func (_m *MockClient) PublicVersion() msp.Identity {
	ret := _m.ctrl.Call(_m, "PublicVersion")
	ret0, _ := ret[0].(msp.Identity)
	return ret0
}

// PublicVersion indicates an expected call of PublicVersion
func (_mr *MockClientMockRecorder) PublicVersion() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "PublicVersion", reflect.TypeOf((*MockClient)(nil).PublicVersion))
}

// SelectionProvider mocks base method
func (_m *MockClient) SelectionProvider() fab.SelectionProvider {
	ret := _m.ctrl.Call(_m, "SelectionProvider")
	ret0, _ := ret[0].(fab.SelectionProvider)
	return ret0
}

// SelectionProvider indicates an expected call of SelectionProvider
func (_mr *MockClientMockRecorder) SelectionProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectionProvider", reflect.TypeOf((*MockClient)(nil).SelectionProvider))
}

// Serialize mocks base method
func (_m *MockClient) Serialize() ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Serialize")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Serialize indicates an expected call of Serialize
func (_mr *MockClientMockRecorder) Serialize() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Serialize", reflect.TypeOf((*MockClient)(nil).Serialize))
}

// Sign mocks base method
func (_m *MockClient) Sign(_param0 []byte) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Sign", _param0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign
func (_mr *MockClientMockRecorder) Sign(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Sign", reflect.TypeOf((*MockClient)(nil).Sign), arg0)
}

// SigningManager mocks base method
func (_m *MockClient) SigningManager() core.SigningManager {
	ret := _m.ctrl.Call(_m, "SigningManager")
	ret0, _ := ret[0].(core.SigningManager)
	return ret0
}

// SigningManager indicates an expected call of SigningManager
func (_mr *MockClientMockRecorder) SigningManager() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SigningManager", reflect.TypeOf((*MockClient)(nil).SigningManager))
}

// UserStore mocks base method
func (_m *MockClient) UserStore() msp.UserStore {
	ret := _m.ctrl.Call(_m, "UserStore")
	ret0, _ := ret[0].(msp.UserStore)
	return ret0
}

// UserStore indicates an expected call of UserStore
func (_mr *MockClientMockRecorder) UserStore() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UserStore", reflect.TypeOf((*MockClient)(nil).UserStore))
}

// Verify mocks base method
func (_m *MockClient) Verify(_param0 []byte, _param1 []byte) error {
	ret := _m.ctrl.Call(_m, "Verify", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify
func (_mr *MockClientMockRecorder) Verify(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Verify", reflect.TypeOf((*MockClient)(nil).Verify), arg0, arg1)
}
